# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180801_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(default=b'helo', max_length=500),
        ),
    ]
